"""empty message

Revision ID: 8033700ebd68
Revises: 
Create Date: 2021-05-09 03:23:19.420830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8033700ebd68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PROPERTIES',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('sold_price', sa.Float(), nullable=True),
    sa.Column('soldOn', sa.DateTime(), nullable=True),
    sa.Column('soldDate', sa.DateTime(), nullable=True),
    sa.Column('listedOn', sa.DateTime(), nullable=True),
    sa.Column('style', sa.String(length=255), nullable=True),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PROPERTIES_address'), 'PROPERTIES', ['address'], unique=False)
    op.create_index(op.f('ix_PROPERTIES_latitude'), 'PROPERTIES', ['latitude'], unique=False)
    op.create_index(op.f('ix_PROPERTIES_longitude'), 'PROPERTIES', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PROPERTIES_longitude'), table_name='PROPERTIES')
    op.drop_index(op.f('ix_PROPERTIES_latitude'), table_name='PROPERTIES')
    op.drop_index(op.f('ix_PROPERTIES_address'), table_name='PROPERTIES')
    op.drop_table('PROPERTIES')
    # ### end Alembic commands ###
